### ISSUE TITLE
Single action yaml

### ISSUE THREAD

**Issue by wurstbrot** [devsecopsmaturitymodel/DevSecOps-MaturityModel#43]
As a dsomm developer, I need to put a new action in different maturity levels to compare the usefulness/effort of the action with other actions in other (sub)dimimensions.

As a dsomm adopter, I want to play around with the existing actions in different levels.
Therefore, I need a way to override just the maturity level.

It is not very "handy" to go into a big yaml file and search for the action to adjust the level in it.

One solution is to place every action in a single yaml. What is your solution?

**Comment by ioggstream** [comment]
We should reverse the database, eg:
```
action:
  dimensions: ...
  ...
```


Or we can have

```
actions:
  action-1: ...
  action-2: ..
  action-3: ...
```

and then 

```
dimension-1:
  subdimension-1:
    actions:
    - *action-1
    - *action-2
  subdimension-2:
    actions:
    - *action-4
    - *action-3
```

This needs some thoughts eg it would be complex to adjust actions.


Can you make some concrete examples svp?
