### ISSUE TITLE
Split iso and other specifications in a separate record.

### ISSUE THREAD

**Issue by ioggstream** [devsecopsmaturitymodel/DevSecOps-MaturityModel#52]
## I propose

- to associate standards to a given action, use a list

### Proposal 1

```
references:
- iso27001: xxx

```

### Proposal 2

```
references:
  iso27001-2017:
  - xxx1
  - xxx2
  samm2:
  - yyy1
  - yy2

```

### Proposal 3
```
references:
  - samm2:xxx
  - iso27001-2017:xxxx
```
